steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/doing-good-with-tech', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/doing-good-with-tech']
  # Get Cluser
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'clusters', 'get-credentials', 'doing-good-with-tech-cluster', '--zone', 'europe-west2-b']
  # Deploy to cluster
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['run', 'doing-good-with-tech-web', '--image', 'gcr.io/$PROJECT_ID/doing-good-with-tech', '--port', '8080']
  # Expose cluster
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['expose', 'deployment', 'doing-good-with-tech-web', '--type=LoadBalancer', '--port', '80', '--target-port', '8080']
images:
- gcr.io/$PROJECT_ID/doing-good-with-tech

