steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/doing-good-with-tech', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/doing-good-with-tech']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'doing-good-with-tech', '--image', 'gcr.io/$PROJECT_ID/doing-good-with-tech']
images:
- gcr.io/$PROJECT_ID/doing-good-with-tech
